### ISSUE TITLE
Add common emails for HIBP

### ISSUE THREAD

**Issue by theabraxas** [theabraxas/Battalion#10]
Create a list of commonly used generic names of email accounts to feed in to HIBP.  This will be things like: support, info, registrar, webmaster, marketing, hr, ceo, president, orders, sales, and so on.

**Comment by eidolonpg** [comment]
@theabraxas can you please add a list of those that you for sure want to this issue in a separate comment? I'll make sure they get in, it should be pretty fast.

**Comment by eidolonpg** [comment]
Actually I'm just going to integrate a really simple list we can append or revise:

```
support
info
webmaster
marketing
sales
orders
```
