### ISSUE TITLE
Record IP scan was run from to add to report

### ISSUE THREAD

**Issue by theabraxas** [theabraxas/Battalion#12]
**Purpose**
For auditing and benefit to the client, record IP the scan ran from. This will be added to the report (optional?)

**How**

Simple command like below should be sufficient to get the IP (Thanks @001SPARTaN) 

`curl -s ipinfo.io | grep ip | cut -d\" -f4`

Then have it exported in to the report building child process

**Comment by eidolonpg** [comment]
See #31
