### ISSUE TITLE
EyeWitness report not generating

### ISSUE THREAD

**Issue by theabraxas** [theabraxas/Battalion#15]
Fix bug where sometimes eyewitness report is not saved to directory

**Comment by eidolonpg** [comment]
Have any more information on this? I think I might be seeing this as well. It could be another pathing issue like the `wpscan` bug.

**Comment by theabraxas** [comment]
Not getting an EyeWitness directory anywhere or output files in other directories which look like EyeWitness files.

**Comment by theabraxas** [comment]
You MUST use an absolute path for the --out parameter in order for this to run properly.
