### ISSUE TITLE
Convert all output to JSON

### ISSUE THREAD

**Issue by eidolonpg** [theabraxas/Battalion#18]
This is a somewhat sizable task because anything consuming that output now needs to consume JSON. We'll be using `jq` for parsing for the time being. We can break this down into several smaller tasks by focusing on individual output files.

Note that this does _not_ include consolidating output files, etc, just a flat conversion from the existing files. We don't want a post-processing operation, just work with JSON in the first place.

**Comment by eidolonpg** [comment]
`git checkout feature/18-domain-json` -- converting the output of the base domain scan via DNSRecon to JSON.

**Comment by theabraxas** [comment]
All outputs now JSON with exception of NMAP which is XML output. @eidolonpg do we want to use a tool like `xml2json` or handle it ourselves?

**Comment by eidolonpg** [comment]
I'm not certain we want a flat to JSON conversion for it, and that's also another dependency. If we can identify the important things from a given scan that's probably a straightforward conversion we can own.
