### ISSUE TITLE
More comprehensive setup documentation

### ISSUE THREAD

**Issue by eidolonpg** [theabraxas/Battalion#22]
Right now we have minimal setup documentation, but it needs to be better. It pretty much only matches my home Ubuntu box. We could have Kali (important), OS X, Windows (low priority), and maybe a couple of gotchas that people have run into. I think that prioritizing Kali setup is preferable.

On that note, an extra effort would be to make a one-stop script that sets up Battalion on the latest Kali after Clone.

Thoughts?

**Comment by theabraxas** [comment]
I agree, will try to do this by 11/14

**Comment by theabraxas** [comment]
Completed Kali linux setup documentation, will create one for Ubuntu 16 as well - others can contribute a RHEL/CentOS guide if possible.

Will attempt to update as project develops. Will also attempt to build an automatic full setup script.
