### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by petermbenjamin** [theabraxas/Battalion#44]
It would be cool if this application is bundled in a docker container for easier deployments and installations (just run `docker pull <container>` to install or `docker run <container>` to install & run it)

#### To run interactively
- `docker run -it battalion` (this would drop you into an interactive shell inside the container)

#### To run a job/task
- `docker run battalion --name Test --out /some/path --domain "example.com"`

**Comment by eidolonpg** [comment]
For a number of reasons, very yes!

**Comment by theabraxas** [comment]
@petermbenjamin due to some design issues with how battalion is set it, it doesn't look like docker is a great option for individuals to install. Will probably utilize for a service we may create.

Closing for now unless you think there's a sensible way to do it!
