### ISSUE TITLE
Change 'Probable emails' to 'possible emails', 'probable emails' and 'detected email format'

### ISSUE THREAD

**Issue by theabraxas** [theabraxas/Battalion#6]
In the `user` folder, add a file with all variations (remove the variation notation 'lif,lfi,fl_dot', etc.) as 'possible emails' and also create a separate file on correct format detection which will indicate the format rule used, lastly create a list of all people in the 'detected' email format as 'probable emails'

**Comment by eidolonpg** [comment]
As part of my other changes to the core HIBP logic this is almost done naturally. The only part I still need to do is output the probable emails to a separate file. Then in the end we will have...

- Possible emails
- Compromised style (can change to format if desired)
- Probable emails
- Compromised emails
